project:
  type: website

website:
  title: "dig-std"
  navbar:
    left:
      - href: index.qmd
        text: "Lista zmiennych"
      - href: outcome.qmd
        text: "Outcome: death or hosp from hf"
      - href: ventricular.qmd
        text: "Outcome: hosp from ventr arrythm"
      - href: prior-dig.qmd
        text: "Prior digoxin use"
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
